version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ml_constructor_db
    environment:
      POSTGRES_DB: ml_constructor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ml_constructor_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ml_constructor_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: ml_constructor
      SECRET_KEY: your-super-secret-key-change-this-in-production
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/saved_models:/app/saved_models
    depends_on:
      - db
    networks:
      - ml_constructor_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ml_constructor_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ml_constructor_network

volumes:
  postgres_data:

networks:
  ml_constructor_network:
    driver: bridge